<a href="https://colab.research.google.com/github/minwoo111111/AI-Python/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#패키지: 모듈을 포함하는 디렉터리. 파이썬 프로그램을 구성하는 여러 모듈들을 그룹화하여 관리할 수 있게 해주는 도구. 모듈을 계층적으로 구조화해허 더 큰 프로젝트를 구성하는 데 사용함.
      #외부패키지: 내부패키지와 달리 설치 과정이 필요함.
      #외부패키지의 설치: pip *명령어*를 사용하여 설치.   미니콘다에서는 conda 명령어로 설치.
      #아나콘다는 다양한 패키지가 미리 설치돼있어 편리. 무겁단 단점은 있지만...
#모듈: 파이썬 코드를 담고 있는 파이썬 파일임. *.py    모듈이 담고 있는 정의를 재사용해 쓸 수 있는 것.
#패키지와 모듈의 관계: 패키지는 서로 연관성 있는 모듈의 집합이고, 모듈은 패키지의 구성 요소이다.

In [29]:
pip install numpy  #numpy 패키지를 컴퓨터에 설치


In [ ]:
pip install pandas #pandas 패키지를 컴퓨터에 설치

In [30]:
import numpy #넘파이 기본 설정. 컴퓨터에 패키지를 설치하고 나서 import문으로 불러와야 함.
import pandas #컴퓨터에 패키지를 설치하지도 않은 pandas를 import해오는 것은 불가능함. Module not found error가 나타남.

#패키지들을 별칭을 사용해 불러올 수 있음. 패키지 이름을 줄이고 코드를 간결하게 만들 수 있기 때문임.
import numpy as np  #numpy를 np라는 이름으로 줄여불러라
import pandas as pd  #pandas를 pd라는 이름으로 줄여불러라

print(np.__version__)  #넘파이 버전 확인

1.25.2


In [ ]:
pip list

In [ ]:
#넘파이를 쓰는 이유: 파이썬에서 벡터, 행렬 등의 ***다차원 배열***을 효율적으로 처리할 수 있도록 / 큰 배열과 행렬 연산에 필요한 다양한 함수를 제공
    #효율적 데이터 저장과 접근, 데이터 연산 및 분석.
    #n차원의 배열을 효과적으로 다룰 수 있음.

In [33]:
#numpy는 다양한 방법으로 배열을 생성.

#np.array(): 리스트나 튜플로부터 배열 생성.

#1차원 배열
arr1d=np.array([1,2,3,4,5])
print(arr1d)

#이 데이터에 대한 배열의 형태, 차원, 데이터 타입 확인하려면 속성을 사용하면 됨
print("Shape:", arr2d.ndim)  #등등

lst=[1,2,3]
arr=np.array(lst)

print(type(lst),lst)  #둘은 타입이 다르다. 이건 리스트고 밑에껀 넘파이의 객체
print(type(arr),arr)

[1 2 3 4 5]


NameError: name 'arr2d' is not defined

In [ ]:
#np.arrange(): 일정한 간격의 값들을 가진 배열 생성

import numpy as np
# 0부터 9까지
arr = np.arange(10)
print(arr)
# 2부터 19까지, 간격은 2
arr = np.arange(2, 20, 2)
print(arr)


In [46]:
#np.zeros(): 모든 값이 0인 배열 생성
import numpy as np
# 1차원 배열
zeros_1d = np.zeros(5)
print(zeros_1d)
# 2차원 배열
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

#np.ones(): 모든 값이 1인 배열 생성
import numpy as np
# 1차원 배열
ones_1d = np.ones(5)
print(ones_1d)
# 2차원 배열
ones_2d = np.ones((3, 4))
print(ones_2d)


#np.random.rand(): 무작위 값들을 가진 배열 생성   #단, 랜덤으로 만들 때 범위는 0~1 사이의 수가 생성됨.
import numpy as np
# 1차원 배열
arr_1d = np.random.rand(5)
print(arr_1d)
# 2차원 배열
arr_2d = np.random.rand((2, 3))
print(arr_2d)

#np.linspace(): 지정한 범위 내에서 균일한 간격의 값들을 가진 배열 생성
import numpy as np
# 0부터 1까지 5개의 값
arr = np.linspace(0, 1, 5)
print(arr)

#다양한 수학, 통계, 공학 함수도 제공.
#np.sum
#np.mean
#np.max
#np.min

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.9202237  0.81354134 0.96877505 0.02979435 0.83695439]


TypeError: 'tuple' object cannot be interpreted as an integer

연습문제

In [50]:
# 최초에 import문으로 패키지를 불러들여야 한다는 것에 유의!!

#1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자.
import numpy as np
arr=np.arange(1,10,2)
print(arr)


#모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자.   <-그니까... 행이 3줄, 열이 4줄인 리스트를 만들라는거인 듯
arr1=np.ones((3, 4))
print(arr1)

#0과 1 사이를 10등분하고자 할 때 등분값 배열을 생성해보자.
arr2=np.linspace(0,1,10)
print(arr2)


#array를 사용한 배열 생성
a=np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20],
     [21,22,23,24,25]]
     )
print(a)

print("디멘션 구성:",a.shape)
print("전체 원소의 개수:",a.size)
print("차원의 개수:",a.ndim)
print("데이터 타입:",a.dtype)


#랜덤
arr3=np.random.rand(5)
arr4=np.random.rand(5, 6)
print(arr3)
print(arr4)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
디멘션 구성: (5, 5)
전체 원소의 개수: 25
차원의 개수: 2
데이터 타입: int64
[0.53081558 0.76340216 0.14111507 0.40306085 0.76429151]
[[0.44371779 0.3036046  0.21097056 0.28325294 0.85356762 0.79199652]
 [0.80959823 0.07776315 0.3073369  0.82519405 0.43572339 0.9068409 ]
 [0.9906171  0.26679024 0.44030442 0.68429146 0.57758859 0.54728747]
 [0.52847797 0.53142018 0.24010742 0.95657441 0.69486297 0.49360639]
 [0.01256023 0.70829124 0.05045254 0.16019782 0.87699684 0.02646152]]


In [51]:
arr2=np.linspace(0,1,10)
arr2

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#배열의 인덱싱과 슬라이싱

In [78]:
#A행렬을 생성해보자.
a=np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20],
     [21,22,23,24,25]]
     )

#A의 모양을 출력해보자.
print("A의 모양:", a.shape)

#19값을 추출해보자.
print(a[3,3])

#슬라이싱을 이용하여 [[1,2], [6,7]]값을 추출해보자
print(a[0:2],a[0:2])  #???????????????????

#슬라이싱을 이용하여 [[19,20], [24,25]]값을 추출해보자
print(a[-1:-2, a[-1:-2]])  #???    #뭐어떡하란거지.....

#슬라이싱을 이용하여 0축의 첫번째 행과 두번째 행을 추출해보자  #행만 표현하라는얘기

#슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자.  #행열 다 표현하라는 얘기

SyntaxError: invalid syntax (<ipython-input-78-6721516a4a3a>, line 17)

In [82]:
a=np.array([[[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]],
      [[13,14,15,16],
       [17,18,19,20],
       [21,22,23,24]],
      [[25,26,27,28],
       [29,30,31,32],
       [33,34,35,36]]])


#위와 같은 a행렬을 생성하세요
arr=np.arange(1,37)
arr_3d=arr.reshape(3,4,3)  #3차원배열하삼
arr_3d

#a의 모양과 크기를 출력해보자
print(a.shape)
print(a.size)

#a의 모양을 (3,4,3)으로 변경해보자
a_t=a.t

#a를 1차원 배열로 구성해보자

#뭐어떡하란거지.....